"""Fail-closed fixture geometry contract for the RoboRacer mast; never a hardware release.

One authoritative contract (cad/roboracer/fixture-contract.json) and one checker, reconciling
two implementations that were written independently on 2026-09-11 (PR #17, merged; PR #16,
superseded -- see docs/CAD_REVIEW_DISPOSITION.md):

  * from #17: the reviewed-target schema (`dimensions`, bolt coordinates, indicator access) and
    the observation comparator that returns MODEL_GEOMETRY_MATCH_ONLY -- a comparison of
    supplied CAD observations against reviewed targets, not a release.
  * from #16: the clauses DERIVED FROM THE REGISTER (cad/roboracer/parameters.csv): specimen
    stiffness, minimum fixture stiffness, indicator quantization terms, and one pending clause
    per unmeasured interface. These live under `derived_from_register` and are regenerated by
    --refresh; --check fails when the committed section is stale relative to the register, so
    the contract cannot silently disagree with the parameters it is supposed to bind.

Modes
  --check-draft            schema only (unchanged from #17)
  --geometry OBS.json      compare reviewed targets with CAD observations (unchanged from #17)
  --refresh                rewrite derived_from_register from parameters.csv
  --check                  fail (exit 1) if derived_from_register is stale
  --release                exit 2 REFUSED unless: status is reviewed_model_contract, every
                           target dimension and tolerance is filled, and no derived clause is
                           pending. Pending inputs are filled by inspection or owner decision
                           in the register, never here.
"""
import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT = ROOT / "cad/roboracer/fixture-contract.json"
DIMENSIONS = {
    "tube_volume": "mm^3", "mast_length": "mm", "mast_outer_diameter": "mm",
    "mast_wall_thickness": "mm", "clamp_engagement": "mm", "clamp_bolt_pitch": "mm",
    "lidar_bracket_bolt_pitch": "mm", "optical_center_offset": "mm",
    "actual_load_height": "mm", "root_rotation_station_spacing": "mm",
}
ACCESS = {"tip_x", "tip_y", "root_x", "root_y", "rotation"}


def require(condition, message):
    if not condition:
        raise ValueError(message)


def number(value, positive=False):
    require(type(value) in (int, float) and math.isfinite(value), "unresolved/nonfinite numerical input")
    require(not positive or value > 0, "numerical input must be positive")
    return value


def filled(value):
    require(isinstance(value, str) and bool(value.strip()) and value.strip().lower() not in {"pending", "unknown", "tbd"}, "unresolved identity/source")


def check_draft(contract):
    require(type(contract) is dict and type(contract.get("schema_version")) is int and contract["schema_version"] == 1, "unsupported schema")
    require(contract.get("status") in {"draft_blocked", "reviewed_model_contract"}, "invalid contract status")
    dimensions = contract.get("dimensions")
    require(type(dimensions) is dict and set(dimensions) == set(DIMENSIONS), "missing/extra dimensions")
    for key, unit in DIMENSIONS.items():
        item = dimensions[key]
        require(type(item) is dict and set(item) == {"value", "unit", "tolerance_abs", "source"}, "invalid dimension record")
        require(item["unit"] == unit, "incorrect dimension unit")
        if item["value"] is not None:
            number(item["value"], positive=key != "optical_center_offset")
        if item["tolerance_abs"] is not None:
            number(item["tolerance_abs"], positive=True)
    require(type(contract.get("indicator_access")) is dict and set(contract["indicator_access"]) == ACCESS, "missing indicator access")
    return "DRAFT_BLOCKED" if contract["status"] == "draft_blocked" else "SCHEMA_ONLY"


def coordinates(value):
    require(type(value) is list and len(value) >= 2, "missing bolt coordinates")
    for point in value:
        require(type(point) is list and len(point) == 3, "expected bolt x/y/z")
        for component in point:
            number(component)
    require(len({tuple(p) for p in value}) == len(value), "duplicate bolt coordinates")


# ── register-derived clauses (from PR #16) ──────────────────────────────────────────────
REGISTER = ROOT / "cad/roboracer/parameters.csv"
DERIVED_VERSION = "2026-09-12"
UNITS = {
    "mast_length": "mm", "mast_outer_diameter": "mm", "mast_wall_thickness": "mm",
    "youngs_modulus": "N/mm^2", "density": "kg/m^3", "tip_total_mass": "kg",
    "indicator_resolution_limit": "mm", "fixture_stiffness_ratio_min": "1",
    "force_target_1": "N", "force_target_5": "N",
    "clamp_engagement": "mm", "clamp_bolt_pitch": "mm", "lidar_bracket_bolt_pitch": "mm",
    "optical_center_offset": "mm", "actual_load_height": "mm", "root_rotation_station_spacing": "mm",
}
STATE_RANK = ["pending", "model_assumption", "reported_vendor_nominal", "design_choice",
              "committed_simulation", "protocol"]
ALLOWED_STATES = {"pending", "model_assumption", "reported_vendor_nominal", "design_choice", "committed_simulation",
                  "inspection", "drawing", "calibration_record", "owner_decision", "protocol"}
RELEASE_GRADE = {"inspection", "drawing", "calibration_record", "owner_decision", "protocol"}
PLACEHOLDERS = {"", "tbd", "todo", "x", "?", "n/a", "na", "none", "null", "placeholder", "pending", "unknown", "-", "synthetic", "test"}


class ContractInputError(ValueError):
    """The register cannot support the contract as written. Fail closed."""


def load_register(path=REGISTER):
    import csv
    rows = list(csv.DictReader(Path(path).open(encoding="utf-8", newline="")))
    have = {}
    for row in rows:
        if row["parameter"] in have:
            raise ContractInputError("duplicate parameter in register: " + row["parameter"])
        have[row["parameter"]] = row
    out = {}
    for name, unit in UNITS.items():
        if name not in have:
            raise ContractInputError("required parameter missing from register: " + name)
        r = have[name]
        if r["unit"].strip() != unit:
            raise ContractInputError(f"unit mismatch for {name}: register {r['unit']!r}, contract expects {unit!r}")
        state = r["evidence_state"].strip(); raw = r["value"].strip()
        if state not in ALLOWED_STATES:
            raise ContractInputError(f"unsupported evidence_state {state!r} for {name}; allowed: {sorted(ALLOWED_STATES)}")
        if state != "pending" and r["source"].strip().lower() in PLACEHOLDERS:
            raise ContractInputError(f"{name} carries evidence_state {state!r} with no source; a value without provenance is not evidence")
        if state == "pending":
            if raw:
                raise ContractInputError("pending parameter carries a value; refuse to treat it as measured: " + name)
            out[name] = dict(value=None, state="pending", source=r["source"], release=r["release_requirement"]); continue
        try:
            value = float(raw)
        except ValueError:
            raise ContractInputError(f"non-numeric value for {name}: {raw!r}")
        if not math.isfinite(value) or value <= 0:
            raise ContractInputError(f"value must be finite and positive: {name}={raw}")
        out[name] = dict(value=value, state=state, source=r["source"], release=r["release_requirement"])
    return out


def _state(*names, reg):
    states = [reg[n]["state"] for n in names]
    return min(states, key=lambda s: STATE_RANK.index(s) if s in STATE_RANK else len(STATE_RANK))


def _clause(cid, requirement, inputs, reg, *, value=None, unit=None, formula=None, verification=None, axes=None, note=None):
    pending = [n for n in inputs if reg[n]["state"] == "pending"]
    c = {"id": cid, "requirement": requirement, "inputs": list(inputs),
         "status": "pending" if pending else "evaluable",
         "evidence_state": _state(*inputs, reg=reg) if inputs else "protocol"}
    if pending:
        c["pending_inputs"] = pending; c["release_requirement"] = {n: reg[n]["release"] for n in pending}
    if formula: c["formula"] = formula
    if value is not None: c["value"] = value
    if unit: c["unit"] = unit
    if axes: c["axes"] = axes
    if verification: c["verification"] = verification
    if note: c["note"] = note
    return c


def build_derived(reg):
    """Clauses the register can support now, plus one pending clause per unmeasured interface."""
    L, D, t = (reg[k]["value"] for k in ("mast_length", "mast_outer_diameter", "mast_wall_thickness"))
    E = reg["youngs_modulus"]["value"]
    if 2 * t >= D:
        raise ContractInputError(f"wall {t} mm leaves no bore in a {D} mm tube")
    d = D - 2 * t
    I = math.pi * (D**4 - d**4) / 64
    k = 3 * E * I / L**3
    ratio = reg["fixture_stiffness_ratio_min"]["value"]; res = reg["indicator_resolution_limit"]["value"]
    q_um = res * 1e3 / math.sqrt(12); diff_um = q_um * math.sqrt(2)
    f_lo, f_hi = reg["force_target_1"]["value"], reg["force_target_5"]["value"]
    geom = ("mast_length", "mast_outer_diameter", "mast_wall_thickness", "youngs_modulus")
    clauses = [
        _clause("effective_free_length", "Inspected effective free length from clamp datum to load line equals the registered mast_length", ["mast_length"], reg, value=L, unit="mm", verification=reg["mast_length"]["release"]),
        _clause("specimen_bending_stiffness", "Ideal cantilever stiffness of the registered specimen; the scale every fixture term is compared against", geom, reg, value=k, unit="N/mm", formula="k = 3*E*I/L^3, I = pi*(D^4 - (D-2t)^4)/64", note="Model quantity (E is a model_assumption). Recompute from the as-built stiffness once inspected; not an as-built value."),
        _clause("fixture_translational_stiffness_min", "Load-point fixture translational stiffness >= fixture_stiffness_ratio_min x specimen stiffness on EACH axis at the actual force line", geom + ("fixture_stiffness_ratio_min",), reg, value=ratio * k, unit="N/mm", axes=["x", "y"], formula="k_fixture_min = fixture_stiffness_ratio_min * k", verification="Physical commissioning at the load point; a rigid CAD solid is not stiffness evidence. Ratio does not bound root rotation."),
        _clause("indicator_resolution", "Independent tip AND root indicator stations, each at or below indicator_resolution_limit, with fixed reference supports and recorded measurement directions", ["indicator_resolution_limit"], reg, value=res, unit="mm", axes=["x", "y"], verification="Instrument IDs and calibration records in the campaign evidence"),
        _clause("ideal_tip_signal_range", "Ideal-beam tip displacement across the protocol force range, for count-resolution planning only", geom + ("force_target_1", "force_target_5"), reg, value={"at_force_target_1_um": f_lo / k * 1e3, "at_force_target_5_um": f_hi / k * 1e3}, unit="um", formula="delta = F / k", note="Planning scale; the frozen gate is on the fitted slope, not pointwise counts."),
        _clause("root_rotation_observation", "Root rotation is observed with two spatially separated root stations over a measured baseline; a single root translation channel cannot observe rotation", ["indicator_resolution_limit", "root_rotation_station_spacing", "actual_load_height"], reg, value={"single_station_quantization_std_um": q_um, "differential_quantization_std_um": diff_um, "angular_std_urad": None, "tip_equivalent_um": None}, formula="angular_std_urad = differential_quantization_std_um / root_rotation_station_spacing_mm * 1e3; tip_equivalent_um = angular_std_urad * actual_load_height_mm * 1e-3", note="Quantization-only planning terms assume independent uniform rounding; calibration, hysteresis and drift are still required in the filled error budget."),
        _clause("load_line_height", "Force line height above the clamp datum, measured; equals the lever used in every stiffness and rotation term", ["actual_load_height"], reg, unit="mm"),
        _clause("clamp_engagement", "Root clamp engagement length and fastener configuration reproduce the actual mast root restraint", ["clamp_engagement"], reg, unit="mm"),
        _clause("clamp_bolt_coordinates", "Deck-side clamp bolt pattern measured on the mating datum; full deck CAD not required", ["clamp_bolt_pitch"], reg, unit="mm"),
        _clause("tip_assembly_interface", "Sensor bracket bolt pattern and optical-centre offset from the exact purchased sensor revision and bracket drawing", ["lidar_bracket_bolt_pitch", "optical_center_offset"], reg, unit="mm"),
        _clause("tip_moving_mass", "Tip assembly mass used by the reference model equals the weighed body + bracket + moving cable; no heat-sink plate or hardware added silently", ["tip_total_mass"], reg, value=reg["tip_total_mass"]["value"], unit="kg", verification=reg["tip_total_mass"]["release"], note="Register value is a summed allowance (model_assumption), not a weighed assembly."),
    ]
    return {
        "derived_version": DERIVED_VERSION,
        "source_parameters": "cad/roboracer/parameters.csv",
        "clauses": clauses,
        "evaluable_clauses": [c["id"] for c in clauses if c["status"] == "evaluable"],
        "pending_clauses": [c["id"] for c in clauses if c["status"] == "pending"],
        "not_generated_pending_owner_inputs": sorted({n for c in clauses for n in c.get("pending_inputs", [])}),
        "evidence_note": "Derived values are model quantities from design_choice/model_assumption rows; matching a geometry against them means the fixture model matches the intended design, not that an as-built fixture is stiff enough or that the campaign is ready.",
    }


def refresh(contract, register_path=REGISTER):
    contract = dict(contract); contract["derived_from_register"] = build_derived(load_register(register_path)); return contract


def derived_is_current(contract, register_path=REGISTER):
    return contract.get("derived_from_register") == build_derived(load_register(register_path))


def _is_placeholder(value):
    return not isinstance(value, str) or value.strip().lower() in PLACEHOLDERS or len(value.strip()) < 4


def complete_contract_blockers(contract, register_path=REGISTER):
    """Everything that stops this contract from being a COMPLETE reviewed contract. The same list
    gates --release and --geometry, so the two modes cannot disagree about what a complete
    contract is (review 2026-09-12). Empty list = complete; it says nothing about geometry match
    or physical validation."""
    out = []
    if contract.get("status") != "reviewed_model_contract":
        out.append(f"status is {contract.get('status')!r}, not reviewed_model_contract")
    for key in ("datum", "drawing_revision", "reviewed_by", "bolt_source"):
        if _is_placeholder(contract.get(key)): out.append(f"{key} unfilled or placeholder ({contract.get(key)!r})")
    dims = contract.get("dimensions") or {}
    for key, item in dims.items():
        if item.get("value") is None or item.get("tolerance_abs") is None: out.append(f"dimension {key} has no reviewed target/tolerance")
        elif not (isinstance(item["tolerance_abs"], (int, float)) and 0 < item["tolerance_abs"] <= abs(item["value"]) + 1e-9 if item["value"] else True):
            out.append(f"dimension {key} tolerance {item['tolerance_abs']} is not positive and smaller than the target")
        if _is_placeholder(item.get("source")): out.append(f"dimension {key} source unfilled or placeholder ({item.get('source')!r})")
    # numerical consistency of the targets themselves, not just presence
    try:
        od, wall, L, vol = (dims[k]["value"] for k in ("mast_outer_diameter", "mast_wall_thickness", "mast_length", "tube_volume"))
        if None not in (od, wall, L, vol):
            if not 2 * wall < od: out.append(f"tube targets inconsistent: 2*wall {2*wall} >= OD {od}")
            expect = math.pi / 4 * (od**2 - (od - 2 * wall)**2) * L
            tol = dims["tube_volume"]["tolerance_abs"] or 0
            if abs(vol - expect) > tol: out.append(f"tube_volume target {vol:.6g} inconsistent with OD/wall/length ({expect:.6g}) beyond tolerance {tol}")
    except (KeyError, TypeError):
        pass
    bolts = contract.get("bolt_coordinates_mm")
    if not bolts: out.append("bolt_coordinates_mm unfilled")
    else:
        try: coordinates(bolts)
        except AssertionError as e: out.append(f"bolt_coordinates_mm malformed: {e}")
        except Exception as e: out.append(f"bolt_coordinates_mm malformed: {e}")
    bt = contract.get("bolt_coordinate_tolerance_mm")
    if not (isinstance(bt, (int, float)) and bt > 0): out.append(f"bolt_coordinate_tolerance_mm missing or non-positive ({bt!r})")
    for key, value in (contract.get("indicator_access") or {}).items():
        if _is_placeholder(value): out.append(f"indicator_access.{key} unfilled or placeholder ({value!r})")
    if not derived_is_current(contract, register_path): out.append("derived_from_register is stale relative to the register; run --refresh")
    for cid in (contract.get("derived_from_register") or {}).get("pending_clauses", []):
        out.append(f"derived clause pending: {cid}")
    try:
        reg = load_register(register_path)
        weak = sorted(n for n, v in reg.items() if v["state"] not in RELEASE_GRADE and v["state"] != "pending")
        if weak: out.append("register rows not release-grade (" + ", ".join(f"{n}:{reg[n]['state']}" for n in weak) + ")")
    except ContractInputError as e:
        out.append(f"register unsupported: {e}")
    return out


def release_blockers(contract, register_path=REGISTER):
    """Kept for callers; identical to complete_contract_blockers."""
    return complete_contract_blockers(contract, register_path)


def compare_geometry(contract, observations, register_path=REGISTER):
    check_draft(contract)
    blockers = complete_contract_blockers(contract, register_path)
    require(not blockers, "unresolved: contract is not complete: " + "; ".join(blockers[:4]) + (" ..." if len(blockers) > 4 else ""))
    require(type(observations) is dict, "missing geometry observations")
    for key in ("datum", "drawing_revision"):
        require(observations.get(key) == contract[key], "geometry identity/datum mismatch")
    observed = observations.get("dimensions")
    units = observations.get("units")
    require(type(observed) is dict and set(observed) == set(DIMENSIONS), "missing/extra geometry dimensions")
    require(type(units) is dict and units == DIMENSIONS, "geometry units mismatch")
    for key, item in contract["dimensions"].items():
        expected = number(item["value"], positive=key != "optical_center_offset")
        tolerance = number(item["tolerance_abs"], positive=True)
        filled(item["source"])
        actual = number(observed[key], positive=key != "optical_center_offset")
        require(abs(actual - expected) <= tolerance, f"{key} outside tolerance")
    targets = {key: item["value"] for key, item in contract["dimensions"].items()}
    for values in (targets, observed):
        od, wall = values["mast_outer_diameter"], values["mast_wall_thickness"]
        require(2 * wall < od, "invalid tube wall/OD")
        volume = math.pi / 4 * (od**2 - (od - 2 * wall)**2) * values["mast_length"]
        require(abs(values["tube_volume"] - volume) <= contract["dimensions"]["tube_volume"]["tolerance_abs"], "tube reference-segment volume inconsistent with dimensions")
    coordinates(contract.get("bolt_coordinates_mm"))
    coordinates(observations.get("bolt_coordinates_mm"))
    tolerance = number(contract.get("bolt_coordinate_tolerance_mm"), positive=True)
    expected = contract["bolt_coordinates_mm"]
    actual = observations["bolt_coordinates_mm"]
    require(len(actual) == len(expected), "bolt count mismatch")
    for target, point in zip(expected, actual):
        require(all(abs(a - b) <= tolerance for a, b in zip(target, point)), "bolt coordinate outside tolerance")
    return "MODEL_GEOMETRY_MATCH_ONLY"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--contract", type=Path, default=DEFAULT)
    parser.add_argument("--geometry", type=Path, help="Reviewed CAD observation JSON; not a screenshot")
    parser.add_argument("--check-draft", action="store_true", help="Schema only; never release readiness")
    parser.add_argument("--refresh", action="store_true", help="Rewrite derived_from_register from parameters.csv")
    parser.add_argument("--check", action="store_true", help="Exit 1 if derived_from_register is stale")
    parser.add_argument("--release", action="store_true", help="Exit 2 REFUSED unless every target and derived clause is filled")
    parser.add_argument("--parameters", type=Path, default=REGISTER)
    args = parser.parse_args()
    try:
        contract = json.loads(args.contract.read_text())
        if args.refresh:
            check_draft(contract)
            args.contract.write_text(json.dumps(refresh(contract, args.parameters), indent=2) + "\n")
            d = json.loads(args.contract.read_text())["derived_from_register"]
            print(f"derived_from_register refreshed: {len(d['evaluable_clauses'])} evaluable, {len(d['pending_clauses'])} pending"); return
        if args.check:
            check_draft(contract)
            if not derived_is_current(contract, args.parameters):
                parser.exit(1, "STALE: derived_from_register does not match cad/roboracer/parameters.csv; run --refresh\n")
            print("derived_from_register current"); return
        if args.release:
            check_draft(contract)
            blockers = complete_contract_blockers(contract, args.parameters)
            if blockers:
                parser.exit(2, "REFUSED CONTRACT_INCOMPLETE:\n  - " + "\n  - ".join(blockers) + "\n")
            print("OK CONTRACT_COMPLETE: every target, tolerance, review field, indicator position and register row is filled and\n"
                  "  release-grade, and the targets are numerically consistent. This is an INPUT-REVIEW verdict only: geometry\n"
                  "  comparison (--geometry) and physical validation are separate gates and are not claimed."); return
        if args.check_draft:
            require(args.geometry is None, "draft check cannot compare geometry")
            print(check_draft(contract))
        else:
            require(args.geometry is not None, "missing --geometry observations")
            print(compare_geometry(contract, json.loads(args.geometry.read_text())))
    except (ValueError, OSError, TypeError, KeyError) as exc:
        parser.exit(2, f"BLOCKED: {exc}\n")


if __name__ == "__main__":
    main()
